### ISSUE TITLE
MLE analysis Negative Variance 

### ISSUE THREAD

**Issue by qigongFDA** [DIDSR/iMRMC#127]
In some cases, the MLE analyses Var(A-B) are negative. We faced this problem on small reader size and big case size input file. 

We use R to write a script. It calculate Var(A-B) by Var(A) + Var(B), and use this Var(A-B) to estimate other statistic results.

**Comment by GigiPAN** [comment]
Dear Dr.Gong,

So do you mean, when facing with negative var(A-B), this variance will be replaced by Var(A) + Var(B) in iMRMC package?

**Comment by brandon-gallas** [comment]
I'm not sure the context for this issue. The output of iMRMC contains the components of the variance of the difference: var(A), var(B), cov(A,B), var(A-B). I would ask that you look at and understand those components, how they combine, and decide your next steps
var(A-B) = var(A) + var(B) - 2cov(A,B)

As my response to your Q in an other issue, I ask that you provide your real name and affiliation. It helps me justify the time to respond to you.

**Comment by GigiPAN** [comment]
Thank you Prof.Gallas, we face the negative variance issue when conducting the monte carol simulation, especially when sample size is small and missing data occur. Our current solution for negative variance is to drop this monte carol simulation when analyzing the results.

**Comment by brandon-gallas** [comment]
It is ok to drop simulations if they are rare. I would track how often this happens. If it is not rare, you should find an alternative. You might look to the work of Hillis for a solution for negative variance estimates. That solution can be implemented using the iMRMC output. Such an alternative is on my to-do list.

Thank you.

**Comment by GigiPAN** [comment]
Dear Prof. Brandon,

I am writing regarding our recent simulation study evaluating iMRMC's performance with missing data. In our study, we implemented the Roe and Metz simulation framework to compare iMRMC against the complete case analysis approach under missing data scenarios.

Our findings have revealed some intriguing patterns that we would appreciate your insights on. Under the null hypothesis, we observed that the MLEstat approach yields a notably conservative Type I error rate (2-3%), while the complete case approach maintains the nominal 5% level. Similarly, the MLEstat approach shows higher than nominal 95% confidence interval coverage (approximately 98%), compared to the expected 95% coverage with the complete case approach.

While these results align with statistical theory, we encountered an unexpected finding: the confidence intervals from the complete case approach are actually wider than those from MLEstat. This seems counterintuitive given the conservative Type I error rate and higher coverage probability observed with MLEstat, which would typically suggest wider confidence intervals.

We would greatly value your perspective on this seemingly paradoxical relationship between interval width and coverage properties.

Thank you for your time and expertise.

Best regards,
Zhemin
PhD Candidate in Biostatistics
Tongji University, Shanghai, China

**Comment by GigiPAN** [comment]
![Image](https://github.com/user-attachments/assets/e5761720-8574-4550-8594-08a9615fe25c)

here is one of the simulation scenario result.

**Comment by brandon-gallas** [comment]
The MLE results are not validated for study designs with missing data. Furthermore, I have never proven that the MLE result is actually the MLE result when there is missing data. The MLE results have been misused and cause substantial confusion. We will be removing it from the software. I do not recommend using it in your current study.

As mentioned, Hillis has a method that does not yield negative variance estimates. He has also published work deriving the relationship between his model outputs and the U-statistics decomposition.

I don't know what you mean by "Complete case analysis". To me, that means no missing data. So, I don't understand if you are comparing different methods or different data distributions.

You provide a screen shot of your data output. It is not a screen shot of the output of iMRMC, and I don't know the inputs. So, my ability to help is severely limited.

I don't see you mentioning the U-statistics results. Those results have been validated in many studies and can treat missing data. Yes, the method can produce negative variance estimates, but I have only seen that in rare and simulated cases, and cases with datasets that are clearly too small. Otherwise, as mentioned, I suggest you track how often the negative variance estimates occur and report the limitation. I would be happy to read your work to better understand.
