### ISSUE TITLE
Not Fully Crossed Analysis (Binary Data)

### ISSUE THREAD

**Issue by stevenhurwitt** [DIDSR/iMRMC#153]
Is there any way to manipulate the code to work with a non-fully crossed design? For instance if readers are divided up across the cases (and every reader does **not** read every case), then the AUC values are only a fraction of what they should be. 

Is there any literature on how to adjust for this, or any functionality within the current code?

**Comment by brandon-gallas** [comment]
You are in luck. The code can do it. That's why we have a list-mode primary data format.

Gallas, B. D. & Brown, D. G. (2008), 'Reader Studies for Validation of CAD Systems', Neural Networks Special Conference Issue 21(2), 387-397.

Gallas, B. D.; Pennello, G. A. & Myers, K. J. (2007), 'Multireader Multicase Variance Analysis for Binary Data', J Opt Soc Am A, Special Issue on Image Quality 24(12), B70-B80.

**Comment by stevenhurwitt** [comment]
Thanks! I will look into it in the next few days - the naive way I tried was giving AUC's of around .5 and I assume averaging over all readers (they should have been around .9 with the sample data I was using)

**Comment by GigiPAN** [comment]
> Thanks! I will look into it in the next few days - the naive way I tried was giving AUC's of around .5 and I assume averaging over all readers (they should have been around .9 with the sample data I was using)

@stevenhurwitt Hi Dr.Steven. I`d like to seek your support that have you work out the code for non-fully- crossover design studies based on iMRMC r package?

**Comment by brandon-gallas** [comment]
@GigiPAN You should refer to these wiki pages:
* https://github.com/DIDSR/iMRMC/wiki/Estimate-sensitivity-and-specificity
* https://github.com/DIDSR/iMRMC/wiki/MRMC-analysis-of-binary-data

**Comment by GigiPAN** [comment]
Thank you Prof.Gallas!
