### ISSUE TITLE
can't find AUCperReader.csv in R package

### ISSUE THREAD

**Issue by stevenhurwitt** [DIDSR/iMRMC#161]
Getting an error running the R package on my new machine (using R 4.0.0) using the following:

`fake = read.csv("fake88_nurse6_n252_delta15.csv", header = T, sep = ",")`
`result = doIMRMC(fake)`

error says:

 `Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'C:\Users\steve\AppData\Local\Temp\RtmpuY95Mo/imrmcDir/AUCperReader.csv': No such file or directory`

Dataset is attached.
[fake88_nurse6_n252_delta15.zip](https://github.com/DIDSR/iMRMC/files/4578680/fake88_nurse6_n252_delta15.zip)

Note that running the .jar file works as expected.

**Comment by brandon-gallas** [comment]
The zip file is empty. Unable to test.

Please download the most recent version of iMRMC = 1.2.2. It has better error reporting.

The most likely reasons are that your Java version is too old or not installed at all.

**Comment by stevenhurwitt** [comment]
[fake88_nurse6_n252_delta15.zip](https://github.com/DIDSR/iMRMC/files/4581922/fake88_nurse6_n252_delta15.zip)

Non-empty zip file is attached. I'm using iMRMC, 1.2.2 in R, where can I update the java version? I suspect that's the problem. When I download the DIDSR-iMRMC.zip file I can't find the .jar application.

**Comment by brandon-gallas** [comment]
Look online to update your java version.

The jar file is available as one of the assets of the release: 
* https://github.com/DIDSR/iMRMC/releases/tag/iMRMC-v4.0.3

It is also included in the R package. 
* https://github.com/DIDSR/iMRMC/tree/master/Rpackage/iMRMC/inst/java

You can find it when you install the iMRMC R package. Here it is installed on my computer.
* C:\Users\BDG\Documents\R\win-library\3.6\iMRMC\java

= Test iMRMC-v4.0.2.jar =
The data you sent doesn't appear to work "as expected" with iMRMC-v4.0.3.jar.
* It is missing "BEGIN DATA:"
* When I added "BEGIN DATA:", iMRMC-v4.0.3.jar reported that there was no truth for case
** row = 3
** readerID = 1
** caseID = Reader1
** modalityID = Actual101

The problem is that the first column of your file ("ImageNo") is not expected. When I added BEGIN DATA: and removed the "ImageNo" column iMRMC-v4.0.3.jar completed successfully.

= Test in R =

Everything looks fine here.

* > library(iMRMC)
* > result <- doIMRMC(fileName = "fake88_nurse6_n252_delta15.csv", workDir = "workDir")
* > print(result$perReader$AUCA)
* [1] 0.8095238 0.9523810 0.8095238 0.9523810 0.8095238 0.9523810
* > df <- read.csv("fake88_nurse6_n252_delta15.csv")
* > head(df)
*  ImageNo ReaderID     CaseID   Modality Score
* 1       1 Reader1  Actual101  modalityA      1
* 2       2   truth  Actual101      truth      1
* 3       3 Reader1  Actual102  modalityA      1
* 4       4   truth  Actual102      truth      1
* 5       5 Reader1  Actual103  modalityA      1
* 6       6   truth  Actual103      truth      1
* > result <- doIMRMC(df, workDir = "workDir")
* > print(result$perReader$AUCA)
* [1] 0.8095238 0.9523810 0.8095238 0.9523810 0.8095238 0.9523810

**Comment by stevenhurwitt** [comment]
yeah, sorry, i have a different file i use for the java app.

what is your "workDir" defined as? Is there a specific location the java app outputs these files? If so I could probably just point it to there as a workaround.

when i try to just invoke the java app in R i get the following warning:

`pkgPath <- path.package("iMRMC", quiet = FALSE)
iMRMCjarFullPath <- file.path(pkgPath, "java", iMRMCjar)
iMRMCjar <- "iMRMC-v4.0.3.jar"
iMRMCjarFullPath <- file.path(pkgPath, "java", iMRMCjar)

system2( "java", args = c("-jar", iMRMCjarFullPath, fileName, file.path(workDir, "imrmcDir")), stdout = FALSE, stderr = TRUE)`

warning:

`[1] "a total of 0 lines in header"  "ERROR: No truth for case "     "      row = 2 "               
[4] "      readerID = 1 "           "      caseID = Reader1 "       "      modalityID = Actual101 "
[7] ""  `

despite the fact that row2 has a truth case right below it:

![mrmc_error](https://user-images.githubusercontent.com/7502272/81103852-4120c180-8ed7-11ea-8be3-94c7741f7be9.png)

a little confused about what could be causing this. it also creates the file 'input.imrmc' in my temp directory but does not make the /imrmcDir, presumably because of this warning. again, java app works fine.

**Comment by brandon-gallas** [comment]
Thanks for the feedback.

The problem is with the format of your data. Look closely at the warning you provide. 
_" caseID = Reader1 "_ That's not right.

When working directly with the file input mode in R, it must adhere to the format expected by the java program. Check the [user manual](http://didsr.github.io/iMRMC/000_iMRMC/userManualHTML/4_1_1_study_raw_data.htm?ms=AA%3D%3D&st=MA%3D%3D&sct=MA%3D%3D&mw=MjQw).

When working with a data frame in R, you need a data frame with specific column names: readerID, caseID, modalityID, score. Your column names were different and you had an extra column (ImageNo).

I have added some more error checks and allow the data to include extra columns (when working with a data frame in R). Try the new package iMRMC_1.2.3.tar.gz in the [current release](https://github.com/DIDSR/iMRMC/releases/tag/iMRMC-v4.0.3).

**Comment by stevenhurwitt** [comment]
ahhh ok i'll reformat and try it, thanks for your help!

**Comment by stevenhurwitt** [comment]
ok, now that it's working here is a short tutorial on how to build some additional functionality into the R package (mainly to replicate and extend the Java app). Please let me know if you have any critiques/suggestions, it's a little sparse.

Updated data with correct variable names is attached: [fake88_nurse6_n252_delta15.zip](https://github.com/DIDSR/iMRMC/files/4590127/fake88_nurse6_n252_delta15.zip)

Here is the link to the RPub:
[https://rpubs.com/stevenhurwitt/610294](https://rpubs.com/stevenhurwitt/610294)

**Comment by brandon-gallas** [comment]
Thanks for this. We will evaluate (@DevinHFD). Assuming AOK, the best place for this might be as a wiki page for others to follow. Happy to give you full credit. We are moving to recode the analysis methods with native R rather than using the java app engine. So maybe there will be an opportunity to build a new related function.

Brandon

**Comment by DevinHFD** [comment]
Thanks for linking me here (@brandon-gallas ) and also thanks for the tutorial (@stevenhurwitt ). I will go through the package and transfer the java code to R.
