### ISSUE TITLE
could not find function "doROCcurveMRMC"

### ISSUE THREAD

**Issue by DOCT-Y** [DIDSR/iMRMC#187]
Hello, 
I'm trying to calculate the ROC curves for each reader using the function `doROCcurveMRMC`. However, I encountered an error: `could not find function "doROCcurveMRMC"`. Here is my code:
```r
library(iMRMC)

mrmc_df <- read.csv('E:\\experiment\\results\\mrmc_formatted_data.csv')
roc_curves <- doROCcurveMRMC(mrmc_df)
```
I am using R version 4.2.1, and I have confirmed that the iMRMC package is successfully installed.

Could the issue be that I used the wrong function, or is there something else wrong with my code?

Any comment is highly appreciated.

**Comment by brandon-gallas** [comment]
Please again, I ask that you update your GitHub profile with your real name and affiliation.

Regarding your question: It looks like we documented this function but didn't "export" it. We made this choice since the input to the function is not a standard iMRMC formatted file. We probably shouldn't have documented the function if we weren't exporting it. We have decided to export the function. This is available now from GitHub and will be available from CRAN in a future version of bundled updates.

**ALSO:** You can get all the reader ROC curves by running doIMRMC on your data. Here's a short example:

# Attach package
library(iMRMC)

# Create a sample configuration file
config <- sim.gRoeMetz.config()
# Simulate an MRMC ROC data set
dfMRMC_example <- sim.gRoeMetz(config)

# Run MRMC analysis
result <- doIMRMC(dfMRMC_example)

# Extract tpf and fpf of one reader x one modality (all readers x modalities are available)
tpf <- result$ROC$testA.reader1$tpf
fpf <- result$ROC$testA.reader1$fpf

# Plot the ROC curve
plot(fpf,tpf)

**Comment by DOCT-Y** [comment]
Sorry for the delayed response, and thank you very much for your answer and contribution to this project. The profile has been updated.

I found a quick solution to my question. Simply copy the codes of function `doROCxyMRMC` and `doROCcurveMRMC` to my R script file, and the program will work without error.
