### ISSUE TITLE
Need output reports from iMRMC

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DIDSR/iMRMC#30]
```
Results of face-to-face with end user:

After performing analysis on reader scores, the GUI is a nice way to see the 
data, but I need a written report. PDF would be nice, especially if it was 
un-editable. That way the results would be frozen. Plain text would be ok.

The report should include a time and date stamp, the version number of the 
software, and the full-path and name of the input file.

```

Original issue reported on code.google.com by `Brandon.Gallas` on 25 Mar 2015 at 5:55

**Comment by brandon-gallas** [comment]
@koyousun @qigongFDA @brandon-gallas

Yousun, The errors that qi was running into mostly had to do with his build configuration. He was not including the entire source directory and could not find all the classes. Once we fixed that, we were able to merge your code to the master branch. There are a few details that Qi is completing and then we will close this issue.

Note: The merge wasn't trivial because there were several conflicts. The conflicts were caused because your source was built on an earlier (out-of-date) version of the code and we were several commits past that. Not a big deal. That is going to happen from time to time.

To avoid merge conflicts in the future, everyone should pull updates from the base repository to their branches and forks regularly, especially before beginning any development effort. It is also possible and recommended to pull updates from the base as you are developing. That way there will be fewer conflicts that are easier to resolve. We'd be happy to answer any questions you may have on this.

We are close to a new release. I'm going to find some other easy fixes to implement first and make sure the documentation is adequate (but improving!). I'll let you know if and how you can help if you are willing. One way is to scan the list of issues, but they are not all super clear.

Brandon

**Comment by qigongFDA** [comment]
Brandon and I fixed the error and made the button more uniform with whole software. We have merged the update to master branch.

**Comment by qigongFDA** [comment]
@kholee  @koyousun  @jenjong 
Hello everyone,

Today, we read the exported file in detail, and we have a question. We want to know, why do the results appear twice in the exported file? (such as, ****BDG Results**** and  ****BDG Output Results****). And why are you only printing some of the tabled data in each of those sections? Thank you very much.

Regards,
Qi

**Comment by qigongFDA** [comment]
I think the result is this. 

"BDG Result" is sizing predict analysis.

"BDG Output Results" is statpanel analysis. 

We have created a new issue to export them separately (issue 76). Do you think we should close this issue? Thank you.

**Comment by koyousun** [comment]
@qigongFDA 
"BDG Result" had been there before I joined the project. "BDG Output Results"  is what I added. I am not sure if "BDG Result" is for sizing predict analysis. Thank you.

**Comment by qigongFDA** [comment]
@koyousun 
Yes. As my last comment, we think "BDG Result" is for sizing. And "BDG Output Results" is for statpanel. Thank you very much.

**Comment by brandon-gallas** [comment]
thank you both. Qi has been adding to and revising the software output to serve more purposes. The execution of this task has helped us to get to this point. I am now closing it.
